const User = require('../models/User');
const jwt = require('jsonwebtoken');
const BaseController = require('./BaseController');
const MailSender = require('../mailer/mail');
require('dotenv').config();

class LoginController extends BaseController {
  constructor() {
    super();
    this.MailSender = new MailSender();
  }

  async registerUser(req, res) {
    try {
      const { name, email, phoneNumber, password, address, landType } = req.body;
      
      // Validation
      if (!name || !email || !phoneNumber || !password || !address || !landType) {
        return res.status(400).send(this.responseFailed('All fields are required'));
      }

      // Check if user already exists
      const existingUser = await User.findOne({ 
        $or: [{ email }, { phoneNumber }] 
      });
      
      if (existingUser) {
        return res.status(400).send(this.responseFailed('User already exists with this email or phone number'));
      }

      // Create user - OTP will be auto-generated by pre-save middleware
      const user = await User.create({
        name,
        email,
        phoneNumber,
        password,
        address,
        landType
      });

      // Send OTP email
      this.MailSender.mailToSomeone(email, user.otp);

      return res.status(201).send(this.responseSuccess('Registration successful. Please verify OTP.', {
        userId: user._id,
        email: user.email,
        name: user.name,
        message: 'OTP sent to your email'
      }));
    } catch (err) {
      console.error('Registration error:', err);
      
      if (err.name === 'ValidationError') {
        const errors = Object.values(err.errors).map(error => error.message);
        return res.status(400).send(this.responseFailed(errors.join(', ')));
      }
      
      if (err.code === 11000) {
        return res.status(400).send(this.responseFailed('Email or phone number already exists'));
      }
      
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async login(req, res) {
    try {
      const { email, password } = req.body;
      
      // Find user with password selected
      const user = await User.findOne({ email }).select('+password +otpVerified');
      
      if (!user) {
        return res.status(400).send(this.responseFailed('Invalid email or password'));
      }

      // Check if email is verified
      if (!user.otpVerified) {
        return res.status(400).send(this.responseFailed('Please verify your email using OTP'));
      }

      // Check if user is active
      if (!user.isActive) {
        return res.status(400).send(this.responseFailed('Account is deactivated'));
      }

      // Compare password
      const isPasswordValid = await user.comparePassword(password);
      
      if (isPasswordValid) {
        // Generate JWT token
        const token = jwt.sign(
          {
            userId: user._id,
            email: user.email,
            name: user.name,
            role: user.role
          },
          process.env.JWT_TOKEN_KEY,
          { expiresIn: '7d' }
        );

        // Store token and update last login
        user.accessToken = token;
        user.lastLogin = new Date();
        await user.save({ validateBeforeSave: false });

        return res.status(200).send(this.responseSuccess('Login successful', {
          access_token: token,
          user: {
            id: user._id,
            name: user.name,
            email: user.email,
            phoneNumber: user.phoneNumber,
            address: user.address,
            landType: user.landType,
            role: user.role
          }
        }));
      } else {
        return res.status(400).send(this.responseFailed('Invalid credentials'));
      }
    } catch (err) {
      console.error('Login error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async verifyOtp(req, res) {
    try {
      const { email, otp } = req.body;
      
      const user = await User.findOne({ email }).select('+otp +otpExpires');
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      // Check OTP
      if (user.isValidOTP(otp)) {
        // Mark OTP as verified
        user.otpVerified = true;
        user.otp = undefined;
        user.otpExpires = undefined;
        user.isVerified = true;
        await user.save({ validateBeforeSave: false });

        return res.status(200).send(this.responseSuccess('OTP verified successfully'));
      } else {
        return res.status(400).send(this.responseFailed('Invalid or expired OTP'));
      }
    } catch (err) {
      console.error('OTP verification error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async resendOtp(req, res) {
    try {
      const { email } = req.body;
      
      const user = await User.findOne({ email }).select('+otp +otpExpires');
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      // Generate new OTP
      const otp = user.generateOTP();
      await user.save({ validateBeforeSave: false });

      // Send OTP email
      this.MailSender.mailToSomeone(email, otp);

      return res.status(200).send(this.responseSuccess('OTP resent successfully'));
    } catch (err) {
      console.error('Resend OTP error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async getUserProfile(req, res) {
    try {
      const token = req.headers.authorization?.replace('Bearer ', '') || 
                    req.headers.accesstoken;
      
      if (!token) {
        return res.status(401).send(this.responseFailed('Access token required'));
      }

      // Verify token and get user
      const decoded = jwt.verify(token, process.env.JWT_TOKEN_KEY);
      const user = await User.findById(decoded.userId);
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      return res.status(200).send(this.responseSuccess('Profile retrieved successfully', user));
    } catch (err) {
      console.error('Get profile error:', err);
      if (err.name === 'JsonWebTokenError') {
        return res.status(401).send(this.responseFailed('Invalid token'));
      }
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async updateProfile(req, res) {
    try {
      const token = req.headers.authorization?.replace('Bearer ', '') || 
                    req.headers.accesstoken;
      
      if (!token) {
        return res.status(401).send(this.responseFailed('Access token required'));
      }

      const decoded = jwt.verify(token, process.env.JWT_TOKEN_KEY);
      const user = await User.findById(decoded.userId);
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      // Update allowed fields
      const allowedUpdates = ['name', 'address', 'landType', 'profileImage'];
      const updates = {};
      
      allowedUpdates.forEach(field => {
        if (req.body[field] !== undefined) {
          updates[field] = req.body[field];
        }
      });

      // Apply updates
      Object.keys(updates).forEach(key => {
        user[key] = updates[key];
      });

      await user.save();

      return res.status(200).send(this.responseSuccess('Profile updated successfully', user));
    } catch (err) {
      console.error('Update profile error:', err);
      if (err.name === 'JsonWebTokenError') {
        return res.status(401).send(this.responseFailed('Invalid token'));
      }
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async changePassword(req, res) {
    try {
      const token = req.headers.authorization?.replace('Bearer ', '') || 
                    req.headers.accesstoken;
      const { currentPassword, newPassword } = req.body;
      
      if (!token) {
        return res.status(401).send(this.responseFailed('Access token required'));
      }

      const decoded = jwt.verify(token, process.env.JWT_TOKEN_KEY);
      const user = await User.findById(decoded.userId).select('+password');
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      // Verify current password
      const isValidPassword = await user.comparePassword(currentPassword);
      if (!isValidPassword) {
        return res.status(400).send(this.responseFailed('Current password is incorrect'));
      }

      // Update password
      user.password = newPassword;
      await user.save();

      return res.status(200).send(this.responseSuccess('Password changed successfully'));
    } catch (err) {
      console.error('Change password error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async logout(req, res) {
    try {
      const token = req.headers.authorization?.replace('Bearer ', '') || 
                    req.headers.accesstoken;
      
      if (!token) {
        return res.status(401).send(this.responseFailed('Access token required'));
      }

      const decoded = jwt.verify(token, process.env.JWT_TOKEN_KEY);
      const user = await User.findById(decoded.userId);
      
      if (user) {
        user.accessToken = undefined;
        await user.save({ validateBeforeSave: false });
      }

      return res.status(200).send(this.responseSuccess('Logged out successfully'));
    } catch (err) {
      console.error('Logout error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  // Admin functions
  async getAllUsers(req, res) {
    try {
      const users = await User.find({})
        .sort({ createdAt: -1 });
      
      return res.status(200).send(this.responseSuccess('Users retrieved successfully', users));
    } catch (err) {
      console.error('Get all users error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async getUserStats(req, res) {
    try {
      const stats = await User.getStats();
      return res.status(200).send(this.responseSuccess('Statistics retrieved successfully', stats));
    } catch (err) {
      console.error('Get stats error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  // Authentication middleware
  async authenticate(req, res, next) {
    try {
      const token = req.headers.authorization?.replace('Bearer ', '') || 
                    req.headers.accesstoken;
      
      if (!token) {
        return res.status(401).send(this.responseFailed('Access token required'));
      }

      const decoded = jwt.verify(token, process.env.JWT_TOKEN_KEY);
      const user = await User.findById(decoded.userId);
      
      if (!user) {
        return res.status(401).send(this.responseFailed('User not found'));
      }

      if (!user.isActive) {
        return res.status(401).send(this.responseFailed('Account is deactivated'));
      }

      req.user = user;
      next();
    } catch (err) {
      console.error('Authentication error:', err);
      if (err.name === 'JsonWebTokenError') {
        return res.status(401).send(this.responseFailed('Invalid token'));
      }
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  // Admin middleware
  async isAdmin(req, res, next) {
    if (req.user && req.user.role === 'admin') {
      next();
    } else {
      return res.status(403).send(this.responseFailed('Access denied. Admin only.'));
    }
  }
}

module.exports = LoginController;