const User = require('../models/User');
const CryptoJS = require('crypto-js');
const jwt = require('jsonwebtoken');
const messages = require('../public/messages/messages');
const BaseController = require('./BaseController');
const MailSender = require('../mailer/mail');
require('dotenv').config();

class LoginController extends BaseController {
  constructor() {
    super();
    this.MailSender = new MailSender();
  }

  async login(req, res) {
    try {
      const { email, password } = req.body;
      
      // Find user with password selected
      const user = await User.findOne({ email }).select('+password +otpVerified');
      
      if (!user) {
        return res.status(400).send(this.responseFailed('Invalid email or password'));
      }

      // Check if email is verified
      if (!user.otpVerified) {
        return res.status(400).send(this.responseFailed('Please verify your email using OTP'));
      }

      // Check if user is active
      if (!user.isActive) {
        return res.status(400).send(this.responseFailed('Account is deactivated'));
      }

      // Compare password using bcrypt
      const isPasswordValid = await user.comparePassword(password);
      
      // Alternative: If using CryptoJS encryption instead of bcrypt
      // var bytes = CryptoJS.AES.decrypt(user.password, process.env.PASSWORD_KEY);
      // var deCryptedPassword = bytes.toString(CryptoJS.enc.Utf8);
      // const isPasswordValid = password === deCryptedPassword;

      if (isPasswordValid) {
        const payload = {
          email: user.email,
          userId: user._id,
          phoneNumber: user.phoneNumber,
          name: user.name
        };
        
        const secret = process.env.JWT_TOKEN_KEY;
        const token = jwt.sign(payload, secret, { expiresIn: '7d' });

        // Store token in user document (simpler than separate collection)
        user.accessToken = token;
        await user.save({ validateBeforeSave: false });

        return res.status(200).send(this.responseSuccess(messages.login_messages.login_success, { 
          access_token: token,
          user: {
            id: user._id,
            name: user.name,
            email: user.email,
            phoneNumber: user.phoneNumber
          }
        }));
      } else {
        return res.status(400).send(this.responseFailed('Invalid credentials'));
      }
    } catch (err) {
      console.error('Login error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async registerUser(req, res) {
    try {
      const { name, email, phoneNumber, password, address, landType } = req.body;
      
      // Validate required fields
      if (!name || !email || !phoneNumber || !password || !address || !landType) {
        return res.status(400).send(this.responseFailed('All fields are required'));
      }

      // Check if user already exists
      const existingUser = await User.findOne({ 
        $or: [{ email }, { phoneNumber }] 
      });
      
      if (existingUser) {
        return res.status(400).send(this.responseFailed('User already exists with this email or phone number'));
      }

      // Create user (password will be hashed by pre-save middleware)
      const user = await User.create({
        name,
        email,
        phoneNumber,
        password, // Will be hashed by pre-save middleware
        address,
        landType
        // OTP will be auto-generated by pre-save middleware
      });

      // Send OTP email
      this.MailSender.mailToSomeone(email, user.otp);

      return res.status(201).send(this.responseSuccess('User created successfully. Please verify OTP.', {
        userId: user._id,
        email: user.email,
        name: user.name,
        message: 'OTP sent to your email'
      }));
    } catch (err) {
      console.error('Registration error:', err);
      
      // Handle validation errors
      if (err.name === 'ValidationError') {
        const errors = Object.values(err.errors).map(error => error.message);
        return res.status(400).send(this.responseFailed(errors.join(', ')));
      }
      
      // Handle duplicate key error
      if (err.code === 11000) {
        return res.status(400).send(this.responseFailed('Email or phone number already exists'));
      }
      
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async getUserList(req, res) {
    try {
      const users = await User.find({})
        .select('-password -otp -__v -accessToken')
        .sort({ createdAt: -1 });
      
      return res.status(200).send(this.responseSuccess('User list retrieved successfully', users));
    } catch (err) {
      console.error('Get user list error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async setPasscode(req, res) {
    try {
      const { user_id, pass_code } = req.body;
      
      // Check if user exists
      const user = await User.findById(user_id).select('+passcode');
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      // Set or update passcode
      user.passcode = pass_code;
      await user.save({ validateBeforeSave: false });

      return res.status(200).send(this.responseSuccess('Passcode set successfully'));
    } catch (err) {
      console.error('Set passcode error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async checkPasscode(req, res) {
    try {
      const { user_id, pass_code } = req.body;
      
      const user = await User.findById(user_id).select('+passcode');
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      if (!user.passcode) {
        return res.status(400).send(this.responseFailed('Passcode not set for this user'));
      }

      if (user.passcode === pass_code) {
        return res.status(200).send(this.responseSuccess('Passcode verified successfully'));
      } else {
        return res.status(400).send(this.responseFailed('Invalid passcode'));
      }
    } catch (err) {
      console.error('Check passcode error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async resendOtp(req, res) {
    try {
      const { email } = req.body;
      
      const user = await User.findOne({ email }).select('+otp +otpExpires');
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      // Generate new OTP
      const otp = user.generateOTP();
      await user.save({ validateBeforeSave: false });

      // Send OTP email
      this.MailSender.mailToSomeone(email, otp);

      return res.status(200).send(this.responseSuccess('OTP resent successfully'));
    } catch (err) {
      console.error('Resend OTP error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async checkOtp(req, res) {
    try {
      const { email, otp } = req.body;
      
      const user = await User.findOne({ email }).select('+otp +otpExpires +otpVerified');
      
      if (!user) {
        return res.status(404).send(this.responseFailed('User not found'));
      }

      // Check OTP
      if (user.isValidOTP(otp)) {
        // Mark OTP as verified
        user.otpVerified = true;
        user.otp = undefined;
        user.otpExpires = undefined;
        user.isVerified = true;
        await user.save({ validateBeforeSave: false });

        // Generate JWT token
        const payload = {
          email: user.email,
          userId: user._id,
          phoneNumber: user.phoneNumber,
          name: user.name
        };
        
        const secret = process.env.JWT_TOKEN_KEY;
        const token = jwt.sign(payload, secret, { expiresIn: '7d' });

        // Store token
        user.accessToken = token;
        await user.save({ validateBeforeSave: false });

        return res.status(200).send(this.responseSuccess('OTP verified successfully', {
          accessToken: token,
          user: {
            id: user._id,
            name: user.name,
            email: user.email,
            phoneNumber: user.phoneNumber
          }
        }));
      } else {
        return res.status(400).send(this.responseFailed('Invalid or expired OTP'));
      }
    } catch (err) {
      console.error('Check OTP error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  async checkToken(token) {
    try {
      if (!token) return null;
      
      // Verify JWT token
      const decoded = jwt.verify(token, process.env.JWT_TOKEN_KEY);
      
      // Find user with this token
      const user = await User.findOne({ 
        _id: decoded.userId,
        accessToken: token,
        isActive: true 
      }).select('name email phoneNumber');
      
      if (!user) return null;
      
      return {
        name: user.name,
        email: user.email,
        user_id: user._id,
        phoneNumber: user.phoneNumber
      };
    } catch (err) {
      console.error('Check token error:', err);
      return null;
    }
  }

  async userDetail(req, res) {
    try {
      const token = req.headers.authorization?.replace('Bearer ', '') || 
                    req.headers.accesstoken;
      
      if (!token) {
        return res.status(401).send(this.responseFailed('Access token required'));
      }

      const userData = await this.checkToken(token);
      
      if (!userData) {
        return res.status(401).send(this.responseFailed('Invalid or expired token'));
      }

      // Get full user details
      const user = await User.findById(userData.user_id)
        .select('-password -otp -__v -accessToken');
      
      return res.status(200).send(this.responseSuccess('User details retrieved successfully', user));
    } catch (err) {
      console.error('User detail error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }

  // Authentication middleware
  async authenticateToken(req, res, next) {
    try {
      const token = req.headers.authorization?.replace('Bearer ', '') || 
                    req.headers.accesstoken;
      
      if (!token) {
        return res.status(401).send(this.responseFailed('Access token required'));
      }

      const userData = await this.checkToken(token);
      
      if (!userData) {
        return res.status(401).send(this.responseFailed('Invalid or expired token'));
      }

      req.user = userData;
      next();
    } catch (err) {
      console.error('Authentication error:', err);
      return res.status(500).send(this.responseFailed('Internal Server Error'));
    }
  }
}

module.exports = LoginController;